### ISSUE TITLE
Gem naming

### ISSUE THREAD

**Issue by nofxx** [aq1018/mongoid-history#124]
Hello @aq1018 , and thanks for this plugin!

Ok, half my OCD, half maybe avoid future confusion and chaos:
I'm going in plugins to suggest correct gem naming:
http://guides.rubygems.org/name-your-gem/

To fix you could remove lib/mongoid-history.rb or add a deprecated message to it.
gem 'mongoid-history'
require 'mongoid/history'
include Mongoid::History::Tracker
....
All good then. Thank you!

**Comment by adamcrown** [comment]
It looks like there's some good discussion here with a lot of reason to not break things, especially in a revision release but then https://github.com/aq1018/mongoid-history/commit/c8effe8e9c9aa18b6e8fa19c1f3478082ba1ed73 seems to have gone ahead and made that breaking change anyway.

I have a gem with a `~> 0.4` dependency on mongoid-version which shouldn't introduce any breaking changes, according to semantic versioning. My tests ran fine locally because I had 0.4.4 installed and then Travis fails with `cannot load such file -- mongoid-history` because it's using 0.4.5.

Now apparently, I have to go into my gem code and have an `if` condition that checks the gem version being used and does one require or another, which seems very hackey and annoying.

If the change is made it should at least be made in a major version bump. But even then I'm not sure I like the change. The convention is that require files should match the gem name so that `Bundler.require` can handle all of your requires for you without having to require it elsewhere or use the `:require` option. At the very least the README should sepcify `gem 'mongoid-history', require: 'mongoid/history'`.

Could we get this fixed in 0.4.6? I'd be happy to submit a pull-request.

**Comment by johnnyshields** [comment]
@nofxx this is exactly what I was warning about.

**Comment by dblock** [comment]
Hey @adamcrown and @johnnyshields, you're both right. I made a release a bit hastily. I will take a PR please and cut a 0.4.6. I can also yank 0.4.5 if you feel strongly about it.

**Comment by nofxx** [comment]
@dblock let 0.5.0 hit the streets =)
Issue may be closed.

**Comment by dblock** [comment]
You mean 0.4.5?

**Comment by dblock** [comment]
Wait, this is not resolved, no?

**Comment by nofxx** [comment]
If I got it correctly: release 0.4.6 as it were (== 0.4.4) and release 0.5.0 with new fixed naming.
Semantic versioning as adam said.

**Comment by dblock** [comment]
Can I have a pull request for 0.5.0 please?

**Comment by dblock** [comment]
I didn't want to yank 0.4.5 and there're already people using `require 'mongoid/history'`, so undoing that is a bad idea (i did that, then realized this was going to happen, so 0.4.6 is yanked).

I committed https://github.com/aq1018/mongoid-history/commit/8fb5cb8170b396dbe10aadb3b0cccdbc4738cc14 that will let you specify either of the requires and no need to change anything in `Gemfile`. Does this work for everybody?

**Comment by adamcrown** [comment]
Commit https://github.com/aq1018/mongoid-history/commit/8fb5cb8170b396dbe10aadb3b0cccdbc4738cc14 looks good to me.

**Comment by dblock** [comment]
I cut 0.4.7. LMK if that works.
